In [17]:
import os
import shutil
import pandas as pd
from sqlalchemy import create_engine

from dotenv import load_dotenv
from dotenv import find_dotenv
load_dotenv(find_dotenv())

engine = create_engine(os.environ.get('SQLALCHEMY_DATABASE_URI'), echo=True)

In [18]:
nome_relatorio = 'inst_op_cambio_mov_trimestre'
file_name = '{}.csv'.format(nome_relatorio)
df = pd.read_csv(os.path.join('bases', file_name))
df.columns
df.head()

# remove unnamed columns
df.drop('Unnamed: 0', axis=1, inplace=True)
df.drop('Unnamed: 31', axis=1, inplace=True)
df.drop('SR', axis=1, inplace=True)

a_renomear = {
    'Instituição financeira':'nome_if',
    'Código':'co_if',
    'TCB':'tp_consolidado_bancario',
    'Segmento':'segmento',
    'TD':'tp_consolidacao',
    'TC':'tp_controle',
    'Cidade':'cidade',
    'UF':'uf',
    'Data':'dt_base',
    'Exportações':'export_nu_operacoes',
    'Unnamed: 10':'export_valor',
    'Importações':'import_nu_operacoes',
    'Unnamed: 12':'import_valor',
    'Total Primário Comercial':'total_prim_comercial_nu_operacoes',
    'Unnamed: 14':'total_prim_comercial_valor',
    'Transferências do Exterior':'transf_do_exterior_nu_operacoes',
    'Unnamed: 16':'transf_do_exterior_valor',
    'Transferências para o Exterior':'transf_para_exterior_nu_operacoes',
    'Unnamed: 18':'transf_para_exterior_valor',
    'Total Primário Financeiro':'total_prim_financeiro_nu_operacoes',
    'Unnamed: 20':'total_prim_financeiro_valor',
    'Total Primário':'total_prim_nu_operacoes',
    'Unnamed: 22':'total_prim_valor',
    'Interbancário Compra':'interb_compra_nu_operacoes',
    'Unnamed: 24':'interb_compra_valor',
    'Interbancário Venda':'interb_venda_nu_operacoes',
    'Unnamed: 26':'interb_venda_valr',
    'Total Interbancário':'total_interb_nu_operacoes',
    'Unnamed: 28':'total_interb_nu_valor',
    'Total':'total_nu_operacoes',
    'Unnamed: 30':'total_valor',
}

# renomeia as colunas
df = df.rename(columns=a_renomear)

# remove informações que são consolidadas
df = df[df['co_if'].notnull()]

print(df.head())
print(df.dtypes)

# salva os registros no banco de dados
df.to_sql('{}_import'.format(nome_relatorio), con=engine, if_exists='replace')

# executa para ver os resultados retornados que foram importados
df_banco = engine.execute("SELECT * FROM {}_import".format(nome_relatorio)).fetchall()
print(len(df_banco))

print('Registros importados com sucesso.')

     nome_if   co_if tp_consolidado_bancario tp_consolidacao  tp_controle  \
1  SANTANDER  30.379                      b1               C          3.0
2       ITAU  10.069                      b1               C          2.0
3   CITIBANK  30.403                      b1               C          3.0
4       HSBC  51.152                      b1               C          3.0
5         BB  49.906                      b1               C          1.0

   segmento     cidade  uf  dt_base export_nu_operacoes  ...  \
1     199.0  SAO PAULO  SP  12/2014              10.964  ...
2     199.0  SAO PAULO  SP  12/2014              21.047  ...
3     199.0  SAO PAULO  SP  12/2014               5.319  ...
4     199.0   CURITIBA  PR  12/2014               7.691  ...
5     199.0   BRASILIA  DF  12/2014              29.865  ...

  total_prim_nu_operacoes total_prim_valor interb_compra_nu_operacoes  \
1                 203.902       41.601.827                      1.780
2                 307.606       37.628.324                        665
3                 102.920       59.873.949                      1.022
4                 142.829       34.495.657                      1.063
5                 242.775       50.193.893                        919

  interb_compra_valor interb_venda_nu_operacoes interb_venda_valr  \
1          39.866.377                     1.843        39.069.434
2          26.310.394                       693        26.498.273
3           8.492.653                     1.060         9.719.339
4          16.387.352                     1.010        15.017.739
5           6.487.239                       836         6.043.744

  total_interb_nu_operacoes total_interb_nu_valor total_nu_operacoes  \
1                     3.623            78.935.811            207.525
2                     1.358            52.808.667            308.964
3                     2.082            18.211.992            105.002
4                     2.073            31.405.091            144.902
5                     1.755            12.530.982            244.530

   total_valor
1  120.537.638
2   90.436.991
3   78.085.941
4   65.900.748
5   62.724.876

[5 rows x 31 columns]
nome_if                                object
co_if                                  object
tp_consolidado_bancario                object
tp_consolidacao                        object
tp_controle                           float64
segmento                              float64
cidade                                 object
uf                                     object
dt_base                                object
export_nu_operacoes                    object
export_valor                           object
import_nu_operacoes                    object
import_valor                           object
total_prim_comercial_nu_operacoes      object
total_prim_comercial_valor             object
transf_do_exterior_nu_operacoes        object
transf_do_exterior_valor               object
transf_para_exterior_nu_operacoes      object
transf_para_exterior_valor             object
total_prim_financeiro_nu_operacoes     object
total_prim_financeiro_valor            object
total_prim_nu_operacoes                object
total_prim_valor                       object
interb_compra_nu_operacoes             object
interb_compra_valor                    object
interb_venda_nu_operacoes              object
interb_venda_valr                      object
total_interb_nu_operacoes              object
total_interb_nu_valor                  object
total_nu_operacoes                     object
total_valor                            object
dtype: object
2020-02-12 12:41:35,730 INFO sqlalchemy.engine.base.Engine select version()
2020-02-12 12:41:35,732 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,742 INFO sqlalchemy.engine.base.Engine select current_schema()
2020-02-12 12:41:35,744 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,751 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-02-12 12:41:35,753 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,757 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-02-12 12:41:35,758 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,763 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2020-02-12 12:41:35,765 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,774 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2020-02-12 12:41:35,776 INFO sqlalchemy.engine.base.Engine {'name': 'inst_op_cambio_mov_trimestre_import'}
2020-02-12 12:41:35,788 INFO sqlalchemy.engine.base.Engine
CREATE TABLE inst_op_cambio_mov_trimestre_import (
	index BIGINT,
	nome_if TEXT,
	co_if TEXT,
	tp_consolidado_bancario TEXT,
	tp_consolidacao TEXT,
	tp_controle FLOAT(53),
	segmento FLOAT(53),
	cidade TEXT,
	uf TEXT,
	dt_base TEXT,
	export_nu_operacoes TEXT,
	export_valor TEXT,
	import_nu_operacoes TEXT,
	import_valor TEXT,
	total_prim_comercial_nu_operacoes TEXT,
	total_prim_comercial_valor TEXT,
	transf_do_exterior_nu_operacoes TEXT,
	transf_do_exterior_valor TEXT,
	transf_para_exterior_nu_operacoes TEXT,
	transf_para_exterior_valor TEXT,
	total_prim_financeiro_nu_operacoes TEXT,
	total_prim_financeiro_valor TEXT,
	total_prim_nu_operacoes TEXT,
	total_prim_valor TEXT,
	interb_compra_nu_operacoes TEXT,
	interb_compra_valor TEXT,
	interb_venda_nu_operacoes TEXT,
	interb_venda_valr TEXT,
	total_interb_nu_operacoes TEXT,
	total_interb_nu_valor TEXT,
	total_nu_operacoes TEXT,
	total_valor TEXT
)


2020-02-12 12:41:35,791 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,815 INFO sqlalchemy.engine.base.Engine COMMIT
2020-02-12 12:41:35,821 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_inst_op_cambio_mov_trimestre_import_index ON inst_op_cambio_mov_trimestre_import (index)
2020-02-12 12:41:35,824 INFO sqlalchemy.engine.base.Engine {}
2020-02-12 12:41:35,832 INFO sqlalchemy.engine.base.Engine COMMIT
2020-02-12 12:41:35,849 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-02-12 12:41:35,975 INFO sqlalchemy.engine.base.Engine INSERT INTO inst_op_cambio_mov_trimestre_import (index, nome_if, co_if, tp_consolidado_bancario, tp_consolidacao, tp_controle, segmento, cidade, uf, dt_base, export_nu_operacoes, export_valor, import_nu_operacoes, import_valor, total_prim_comercial_nu_operacoes, total_prim_comercial_valor, transf_do_exterior_nu_operacoes, transf_do_exterior_valor, transf_para_exterior_nu_operacoes, transf_para_exterior_valor, total_prim_financeiro_nu_operacoes, total_prim_financeiro_valor, total_prim_nu_operacoes, total_prim_valor, interb_compra_nu_operacoes, interb_compra_valor, interb_venda_nu_operacoes, interb_venda_valr, total_interb_nu_operacoes, total_interb_nu_valor, total_nu_operacoes, total_valor) VALUES (%(index)s, %(nome_if)s, %(co_if)s, %(tp_consolidado_bancario)s, %(tp_consolidacao)s, %(tp_controle)s, %(segmento)s, %(cidade)s, %(uf)s, %(dt_base)s, %(export_nu_operacoes)s, %(export_valor)s, %(import_nu_operacoes)s, %(import_valor)s, %(total_prim_comercial_nu_operacoes)s, %(total_prim_comercial_valor)s, %(transf_do_exterior_nu_operacoes)s, %(transf_do_exterior_valor)s, %(transf_para_exterior_nu_operacoes)s, %(transf_para_exterior_valor)s, %(total_prim_financeiro_nu_operacoes)s, %(total_prim_financeiro_valor)s, %(total_prim_nu_operacoes)s, %(total_prim_valor)s, %(interb_compra_nu_operacoes)s, %(interb_compra_valor)s, %(interb_venda_nu_operacoes)s, %(interb_venda_valr)s, %(total_interb_nu_operacoes)s, %(total_interb_nu_valor)s, %(total_nu_operacoes)s, %(total_valor)s)
2020-02-12 12:41:35,977 INFO sqlalchemy.engine.base.Engine ({'index': 1, 'nome_if': 'SANTANDER', 'co_if': '30.379', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 3.0, 'segmento': 199.0, 'cidade': 'SAO PAULO', 'uf': 'SP', 'dt_base': '12/2014', 'export_nu_operacoes': '10.964', 'export_valor': '6.127.456', 'import_nu_operacoes': '54.730', 'import_valor': '6.733.055', 'total_prim_comercial_nu_operacoes': '65.694', 'total_prim_comercial_valor': '12.860.511', 'transf_do_exterior_nu_operacoes': '48.684', 'transf_do_exterior_valor': '13.366.871', 'transf_para_exterior_nu_operacoes': '89.524', 'transf_para_exterior_valor': '15.374.445', 'total_prim_financeiro_nu_operacoes': '138.208', 'total_prim_financeiro_valor': '28.741.316', 'total_prim_nu_operacoes': '203.902', 'total_prim_valor': '41.601.827', 'interb_compra_nu_operacoes': '1.780', 'interb_compra_valor': '39.866.377', 'interb_venda_nu_operacoes': '1.843', 'interb_venda_valr': '39.069.434', 'total_interb_nu_operacoes': '3.623', 'total_interb_nu_valor': '78.935.811', 'total_nu_operacoes': '207.525', 'total_valor': '120.537.638'}, {'index': 2, 'nome_if': 'ITAU', 'co_if': '10.069', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 2.0, 'segmento': 199.0, 'cidade': 'SAO PAULO', 'uf': 'SP', 'dt_base': '12/2014', 'export_nu_operacoes': '21.047', 'export_valor': '5.327.088', 'import_nu_operacoes': '55.180', 'import_valor': '5.351.991', 'total_prim_comercial_nu_operacoes': '76.227', 'total_prim_comercial_valor': '10.679.079', 'transf_do_exterior_nu_operacoes': '131.046', 'transf_do_exterior_valor': '12.981.332', 'transf_para_exterior_nu_operacoes': '100.333', 'transf_para_exterior_valor': '13.967.913', 'total_prim_financeiro_nu_operacoes': '231.379', 'total_prim_financeiro_valor': '26.949.245', 'total_prim_nu_operacoes': '307.606', 'total_prim_valor': '37.628.324', 'interb_compra_nu_operacoes': '665', 'interb_compra_valor': '26.310.394', 'interb_venda_nu_operacoes': '693', 'interb_venda_valr': '26.498.273', 'total_interb_nu_operacoes': '1.358', 'total_interb_nu_valor': '52.808.667', 'total_nu_operacoes': '308.964', 'total_valor': '90.436.991'}, {'index': 3, 'nome_if': 'CITIBANK', 'co_if': '30.403', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 3.0, 'segmento': 199.0, 'cidade': 'SAO PAULO', 'uf': 'SP', 'dt_base': '12/2014', 'export_nu_operacoes': '5.319', 'export_valor': '3.772.244', 'import_nu_operacoes': '18.912', 'import_valor': '5.234.520', 'total_prim_comercial_nu_operacoes': '24.231', 'total_prim_comercial_valor': '9.006.765', 'transf_do_exterior_nu_operacoes': '27.809', 'transf_do_exterior_valor': '26.246.909', 'transf_para_exterior_nu_operacoes': '50.880', 'transf_para_exterior_valor': '24.620.275', 'total_prim_financeiro_nu_operacoes': '78.689', 'total_prim_financeiro_valor': '50.867.184', 'total_prim_nu_operacoes': '102.920', 'total_prim_valor': '59.873.949', 'interb_compra_nu_operacoes': '1.022', 'interb_compra_valor': '8.492.653', 'interb_venda_nu_operacoes': '1.060', 'interb_venda_valr': '9.719.339', 'total_interb_nu_operacoes': '2.082', 'total_interb_nu_valor': '18.211.992', 'total_nu_operacoes': '105.002', 'total_valor': '78.085.941'}, {'index': 4, 'nome_if': 'HSBC', 'co_if': '51.152', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 3.0, 'segmento': 199.0, 'cidade': 'CURITIBA', 'uf': 'PR', 'dt_base': '12/2014', 'export_nu_operacoes': '7.691', 'export_valor': '3.700.558', 'import_nu_operacoes': '30.656', 'import_valor': '4.693.659', 'total_prim_comercial_nu_operacoes': '38.347', 'total_prim_comercial_valor': '8.394.216', 'transf_do_exterior_nu_operacoes': '34.878', 'transf_do_exterior_valor': '11.950.708', 'transf_para_exterior_nu_operacoes': '69.604', 'transf_para_exterior_valor': '14.150.732', 'total_prim_financeiro_nu_operacoes': '104.482', 'total_prim_financeiro_valor': '26.101.440', 'total_prim_nu_operacoes': '142.829', 'total_prim_valor': '34.495.657', 'interb_compra_nu_operacoes': '1.063', 'interb_compra_valor': '16.387.352', 'interb_venda_nu_operacoes': '1.010', 'interb_venda_valr': '15.017.739', 'total_interb_nu_operacoes': '2.073', 'total_interb_nu_valor': '31.405.091', 'total_nu_operacoes': '144.902', 'total_valor': '65.900.748'}, {'index': 5, 'nome_if': 'BB', 'co_if': '49.906', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 1.0, 'segmento': 199.0, 'cidade': 'BRASILIA', 'uf': 'DF', 'dt_base': '12/2014', 'export_nu_operacoes': '29.865', 'export_valor': '14.258.838', 'import_nu_operacoes': '58.131', 'import_valor': '12.384.353', 'total_prim_comercial_nu_operacoes': '87.996', 'total_prim_comercial_valor': '26.643.191', 'transf_do_exterior_nu_operacoes': '71.162', 'transf_do_exterior_valor': '11.587.221', 'transf_para_exterior_nu_operacoes': '83.617', 'transf_para_exterior_valor': '11.963.481', 'total_prim_financeiro_nu_operacoes': '154.779', 'total_prim_financeiro_valor': '23.550.703', 'total_prim_nu_operacoes': '242.775', 'total_prim_valor': '50.193.893', 'interb_compra_nu_operacoes': '919', 'interb_compra_valor': '6.487.239', 'interb_venda_nu_operacoes': '836', 'interb_venda_valr': '6.043.744', 'total_interb_nu_operacoes': '1.755', 'total_interb_nu_valor': '12.530.982', 'total_nu_operacoes': '244.530', 'total_valor': '62.724.876'}, {'index': 6, 'nome_if': 'JP MORGAN CHASE', 'co_if': '20.107', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 3.0, 'segmento': 199.0, 'cidade': 'SAO PAULO', 'uf': 'SP', 'dt_base': '12/2014', 'export_nu_operacoes': '411', 'export_valor': '1.568.277', 'import_nu_operacoes': '7.253', 'import_valor': '1.968.969', 'total_prim_comercial_nu_operacoes': '7.664', 'total_prim_comercial_valor': '3.537.246', 'transf_do_exterior_nu_operacoes': '2.645', 'transf_do_exterior_valor': '11.301.315', 'transf_para_exterior_nu_operacoes': '6.958', 'transf_para_exterior_valor': '16.298.544', 'total_prim_financeiro_nu_operacoes': '9.603', 'total_prim_financeiro_valor': '27.599.858', 'total_prim_nu_operacoes': '17.267', 'total_prim_valor': '31.137.104', 'interb_compra_nu_operacoes': '898', 'interb_compra_valor': '10.190.212', 'interb_venda_nu_operacoes': '1.023', 'interb_venda_valr': '8.349.990', 'total_interb_nu_operacoes': '1.921', 'total_interb_nu_valor': '18.540.202', 'total_nu_operacoes': '19.188', 'total_valor': '49.677.306'}, {'index': 7, 'nome_if': 'BTG PACTUAL', 'co_if': '49.944', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 2.0, 'segmento': 199.0, 'cidade': 'RIO DE JANEIRO', 'uf': 'RJ', 'dt_base': '12/2014', 'export_nu_operacoes': '82', 'export_valor': '237.037', 'import_nu_operacoes': '132', 'import_valor': '259.194', 'total_prim_comercial_nu_operacoes': '214', 'total_prim_comercial_valor': '496.231', 'transf_do_exterior_nu_operacoes': '1.210', 'transf_do_exterior_valor': '2.819.421', 'transf_para_exterior_nu_operacoes': '1.438', 'transf_para_exterior_valor': '3.530.597', 'total_prim_financeiro_nu_operacoes': '2.648', 'total_prim_financeiro_valor': '6.350.018', 'total_prim_nu_operacoes': '2.862', 'total_prim_valor': '6.846.249', 'interb_compra_nu_operacoes': '405', 'interb_compra_valor': '15.663.721', 'interb_venda_nu_operacoes': '495', 'interb_venda_valr': '16.928.507', 'total_interb_nu_operacoes': '900', 'total_interb_nu_valor': '32.592.228', 'total_nu_operacoes': '3.762', 'total_valor': '39.438.477'}, {'index': 8, 'nome_if': 'BRADESCO', 'co_if': '10.045', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'C', 'tp_controle': 2.0, 'segmento': 199.0, 'cidade': 'OSASCO', 'uf': 'SP', 'dt_base': '12/2014', 'export_nu_operacoes': '17.630', 'export_valor': '7.698.419', 'import_nu_operacoes': '35.173', 'import_valor': '5.772.289', 'total_prim_comercial_nu_operacoes': '52.803', 'total_prim_comercial_valor': '13.470.708', 'transf_do_exterior_nu_operacoes': '69.923', 'transf_do_exterior_valor': '3.423.080', 'transf_para_exterior_nu_operacoes': '58.106', 'transf_para_exterior_valor': '3.749.653', 'total_prim_financeiro_nu_operacoes': '128.029', 'total_prim_financeiro_valor': '7.172.733', 'total_prim_nu_operacoes': '180.832', 'total_prim_valor': '20.643.441', 'interb_compra_nu_operacoes': '1.662', 'interb_compra_valor': '6.388.149', 'interb_venda_nu_operacoes': '1.718', 'interb_venda_valr': '7.014.011', 'total_interb_nu_operacoes': '3.380', 'total_interb_nu_valor': '13.402.160', 'total_nu_operacoes': '184.212', 'total_valor': '34.045.601'}  ... displaying 10 of 3259 total bound parameter sets ...  {'index': 3277, 'nome_if': 'STANDARD CHARTERED BANK (BRASIL) S.A. - BANCO DE INVESTIMENTO', 'co_if': '11.932.017', 'tp_consolidado_bancario': 'b2', 'tp_consolidacao': 'I', 'tp_controle': 3.0, 'segmento': None, 'cidade': 'SAO PAULO', 'uf': 'SP', 'dt_base': '09/2019', 'export_nu_operacoes': '0', 'export_valor': '0', 'import_nu_operacoes': '0', 'import_valor': '0', 'total_prim_comercial_nu_operacoes': '0', 'total_prim_comercial_valor': '0', 'transf_do_exterior_nu_operacoes': '1', 'transf_do_exterior_valor': '2', 'transf_para_exterior_nu_operacoes': '0', 'transf_para_exterior_valor': '0', 'total_prim_financeiro_nu_operacoes': '1', 'total_prim_financeiro_valor': '2', 'total_prim_nu_operacoes': '1', 'total_prim_valor': '2', 'interb_compra_nu_operacoes': '0', 'interb_compra_valor': '0', 'interb_venda_nu_operacoes': '1', 'interb_venda_valr': '15', 'total_interb_nu_operacoes': '1', 'total_interb_nu_valor': '15', 'total_nu_operacoes': '2', 'total_valor': '17'}, {'index': 3278, 'nome_if': 'STATE STREET BRASIL S.A. – BANCO COMERCIAL', 'co_if': '9.274.232', 'tp_consolidado_bancario': 'b1', 'tp_consolidacao': 'I', 'tp_controle': 3.0, 'segmento': None, 'cidade': 'SAO PAULO', 'uf': 'SP', 'dt_base': '09/2019', 'export_nu_operacoes': '0', 'export_valor': '0', 'import_nu_operacoes': '0', 'import_valor': '0', 'total_prim_comercial_nu_operacoes': '0', 'total_prim_comercial_valor': '0', 'transf_do_exterior_nu_operacoes': '0', 'transf_do_exterior_valor': '0', 'transf_para_exterior_nu_operacoes': '3', 'transf_para_exterior_valor': '1', 'total_prim_financeiro_nu_operacoes': '3', 'total_prim_financeiro_valor': '1', 'total_prim_nu_operacoes': '3', 'total_prim_valor': '1', 'interb_compra_nu_operacoes': '0', 'interb_compra_valor': '0', 'interb_venda_nu_operacoes': '0', 'interb_venda_valr': '0', 'total_interb_nu_operacoes': '0', 'total_interb_nu_valor': '0', 'total_nu_operacoes': '3', 'total_valor': '1'})

2020-02-12 12:41:41,626 INFO sqlalchemy.engine.base.Engine COMMIT
2020-02-12 12:41:41,632 INFO sqlalchemy.engine.base.Engine SELECT * FROM inst_op_cambio_mov_trimestre_import
2020-02-12 12:41:41,635 INFO sqlalchemy.engine.base.Engine {}
3259
Registros importados com sucesso.